# Training-only selection of SVM-set versus unified prediction

This experiment uses a nested architecture-validation split drawn exclusively from the training data. It compares the current MiSTIC SVM-set prediction with a single kernel-matched sklearn SVM trained on the knee-ranked unified features. The winning architecture is selected without observing the fixed blind set, both candidates are rebuilt on all available training data, and the selected prediction is evaluated once on the same blind set. Classification uses the current 5-member RBF/weight-0.90 configuration; harder regression uses the current 20-member linear/weight-0.75 configuration.

In [1]:
from pathlib import Path
import sys
repo_root = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'mistic' / 'svmSet.py').exists())
example_dir = repo_root / 'mistic' / 'examples'
if str(example_dir) not in sys.path: sys.path.insert(0, str(example_dir))
from synthetic100_nested_unified_selection import run_experiment
results = run_experiment()
results

Number of Features: 1, Score: 0.667

Number of Features: 10, Score: 0.778

Number of Features: 19, Score: 0.752

Number of Features: 20, Score: 0.761
Number of Features: 100, Score: 0.711

Number of Features: 1, Score: 0.698

Number of Features: 10, Score: 0.796

Number of Features: 19, Score: 0.781

Number of Features: 20, Score: 0.782
Number of Features: 100, Score: 0.768

classification seed=00 complete in 17.1s

Number of Features: 1, Score: 0.731

Number of Features: 10, Score: 0.783

Number of Features: 19, Score: 0.786

Number of Features: 20, Score: 0.779
Number of Features: 100, Score: 0.729

Number of Features: 1, Score: 0.711

Number of Features: 10, Score: 0.800

Number of Features: 19, Score: 0.794

Number of Features: 20, Score: 0.790
Number of Features: 100, Score: 0.772

classification seed=01 complete in 11.9s

Number of Features: 1, Score: 0.654

Number of Features: 10, Score: 0.786

Number of Features: 19, Score: 0.785

Number of Features: 20, Score: 0.784
Number of Features: 100, Score: 0.745

Number of Features: 1, Score: 0.641

Number of Features: 10, Score: 0.735

Number of Features: 19, Score: 0.728

Number of Features: 20, Score: 0.729
Number of Features: 100, Score: 0.703

classification seed=02 complete in 10.3s

Number of Features: 1, Score: 0.709

Number of Features: 10, Score: 0.750

Number of Features: 19, Score: 0.747

Number of Features: 20, Score: 0.738
Number of Features: 100, Score: 0.710

Number of Features: 1, Score: 0.650

Number of Features: 10, Score: 0.795

Number of Features: 19, Score: 0.785

Number of Features: 20, Score: 0.784
Number of Features: 100, Score: 0.770

classification seed=03 complete in 9.6s

Number of Features: 1, Score: 0.638

Number of Features: 10, Score: 0.790

Number of Features: 19, Score: 0.801

Number of Features: 20, Score: 0.793
Number of Features: 100, Score: 0.791

Number of Features: 1, Score: 0.649

Number of Features: 10, Score: 0.792

Number of Features: 19, Score: 0.789

Number of Features: 20, Score: 0.788
Number of Features: 100, Score: 0.761

classification seed=04 complete in 9.7s

Number of Features: 1, Score: 0.743

Number of Features: 10, Score: 0.780

Number of Features: 19, Score: 0.767

Number of Features: 20, Score: 0.767
Number of Features: 100, Score: 0.749

Number of Features: 1, Score: 0.648

Number of Features: 10, Score: 0.781

Number of Features: 19, Score: 0.769

Number of Features: 20, Score: 0.769
Number of Features: 100, Score: 0.760

classification seed=05 complete in 10.6s

Number of Features: 1, Score: 0.689

Number of Features: 10, Score: 0.814

Number of Features: 19, Score: 0.811

Number of Features: 20, Score: 0.817
Number of Features: 100, Score: 0.775

Number of Features: 1, Score: 0.659

Number of Features: 10, Score: 0.781

Number of Features: 19, Score: 0.770

Number of Features: 20, Score: 0.772
Number of Features: 100, Score: 0.769

classification seed=06 complete in 9.8s

Number of Features: 1, Score: 0.642

Number of Features: 10, Score: 0.757

Number of Features: 19, Score: 0.754

Number of Features: 20, Score: 0.750
Number of Features: 100, Score: 0.720

Number of Features: 1, Score: 0.684

Number of Features: 10, Score: 0.754

Number of Features: 19, Score: 0.750

Number of Features: 20, Score: 0.746
Number of Features: 100, Score: 0.724

classification seed=07 complete in 9.5s

Number of Features: 1, Score: 0.706

Number of Features: 10, Score: 0.782

Number of Features: 19, Score: 0.794

Number of Features: 20, Score: 0.794
Number of Features: 100, Score: 0.760

Number of Features: 1, Score: 0.707

Number of Features: 10, Score: 0.755

Number of Features: 19, Score: 0.727

Number of Features: 20, Score: 0.731
Number of Features: 100, Score: 0.724

classification seed=08 complete in 11.5s

Number of Features: 1, Score: 0.667

Number of Features: 10, Score: 0.804

Number of Features: 19, Score: 0.781

Number of Features: 20, Score: 0.773
Number of Features: 100, Score: 0.740

Number of Features: 1, Score: 0.647

Number of Features: 10, Score: 0.774

Number of Features: 19, Score: 0.751

Number of Features: 20, Score: 0.750
Number of Features: 100, Score: 0.729

classification seed=09 complete in 9.8s

Number of Features: 1, Score: 0.708

Number of Features: 10, Score: 0.803

Number of Features: 19, Score: 0.810

Number of Features: 20, Score: 0.808
Number of Features: 100, Score: 0.778

Number of Features: 1, Score: 0.627

Number of Features: 10, Score: 0.706

Number of Features: 19, Score: 0.705

Number of Features: 20, Score: 0.703
Number of Features: 100, Score: 0.702

classification seed=10 complete in 9.7s

Number of Features: 1, Score: 0.706

Number of Features: 10, Score: 0.790

Number of Features: 19, Score: 0.769

Number of Features: 20, Score: 0.769
Number of Features: 100, Score: 0.753

Number of Features: 1, Score: 0.665

Number of Features: 10, Score: 0.805

Number of Features: 19, Score: 0.783

Number of Features: 20, Score: 0.784
Number of Features: 100, Score: 0.759

classification seed=11 complete in 9.5s

Number of Features: 1, Score: 0.706

Number of Features: 10, Score: 0.801

Number of Features: 19, Score: 0.777

Number of Features: 20, Score: 0.783
Number of Features: 100, Score: 0.739

Number of Features: 1, Score: 0.703

Number of Features: 10, Score: 0.816

Number of Features: 19, Score: 0.800

Number of Features: 20, Score: 0.800
Number of Features: 100, Score: 0.766

classification seed=12 complete in 11.7s

Number of Features: 1, Score: 0.690

Number of Features: 10, Score: 0.752

Number of Features: 19, Score: 0.745

Number of Features: 20, Score: 0.743
Number of Features: 100, Score: 0.741

Number of Features: 1, Score: 0.631

Number of Features: 10, Score: 0.758

Number of Features: 19, Score: 0.744

Number of Features: 20, Score: 0.744
Number of Features: 100, Score: 0.722

classification seed=13 complete in 12.3s

Number of Features: 1, Score: 0.714

Number of Features: 10, Score: 0.806

Number of Features: 19, Score: 0.796

Number of Features: 20, Score: 0.792
Number of Features: 100, Score: 0.772

Number of Features: 1, Score: 0.662

Number of Features: 10, Score: 0.797

Number of Features: 19, Score: 0.783

Number of Features: 20, Score: 0.784
Number of Features: 100, Score: 0.760

classification seed=14 complete in 10.1s

Number of Features: 1, Score: 0.759

Number of Features: 10, Score: 0.804

Number of Features: 19, Score: 0.780

Number of Features: 20, Score: 0.782
Number of Features: 100, Score: 0.739

Number of Features: 1, Score: 0.700

Number of Features: 10, Score: 0.844

Number of Features: 19, Score: 0.827

Number of Features: 20, Score: 0.822
Number of Features: 100, Score: 0.799

classification seed=15 complete in 10.0s

Number of Features: 1, Score: 0.709

Number of Features: 10, Score: 0.788

Number of Features: 19, Score: 0.768

Number of Features: 20, Score: 0.766
Number of Features: 100, Score: 0.723

Number of Features: 1, Score: 0.656

Number of Features: 10, Score: 0.762

Number of Features: 19, Score: 0.745

Number of Features: 20, Score: 0.745
Number of Features: 100, Score: 0.727

classification seed=16 complete in 9.9s

Number of Features: 1, Score: 0.649

Number of Features: 10, Score: 0.722

Number of Features: 19, Score: 0.730

Number of Features: 20, Score: 0.729
Number of Features: 100, Score: 0.706

Number of Features: 1, Score: 0.638

Number of Features: 10, Score: 0.777

Number of Features: 19, Score: 0.783

Number of Features: 20, Score: 0.784
Number of Features: 100, Score: 0.760

classification seed=17 complete in 12.1s

Number of Features: 1, Score: 0.672

Number of Features: 10, Score: 0.790

Number of Features: 19, Score: 0.792

Number of Features: 20, Score: 0.789
Number of Features: 100, Score: 0.764

Number of Features: 1, Score: 0.688

Number of Features: 10, Score: 0.770

Number of Features: 19, Score: 0.749

Number of Features: 20, Score: 0.746
Number of Features: 100, Score: 0.730

classification seed=18 complete in 11.6s

Number of Features: 1, Score: 0.682

Number of Features: 10, Score: 0.801

Number of Features: 19, Score: 0.793

Number of Features: 20, Score: 0.794
Number of Features: 100, Score: 0.783

Number of Features: 1, Score: 0.683

Number of Features: 10, Score: 0.762

Number of Features: 19, Score: 0.760

Number of Features: 20, Score: 0.761
Number of Features: 100, Score: 0.741

classification seed=19 complete in 12.8s

Number of Features: 1, Score: 0.175

Number of Features: 10, Score: 0.665

Number of Features: 19, Score: 0.788

Number of Features: 20, Score: 0.799

Number of Features: 100, Score: 0.730

Number of Features: 1, Score: 0.075

Number of Features: 10, Score: 0.658

Number of Features: 19, Score: 0.808

Number of Features: 20, Score: 0.809

Number of Features: 100, Score: 0.784

regression seed=00 complete in 48.2s

Number of Features: 1, Score: 0.210

Number of Features: 10, Score: 0.711

Number of Features: 19, Score: 0.814

Number of Features: 20, Score: 0.818

Number of Features: 100, Score: 0.759

Number of Features: 1, Score: 0.103

Number of Features: 10, Score: 0.670

Number of Features: 19, Score: 0.813

Number of Features: 20, Score: 0.812

Number of Features: 100, Score: 0.791

regression seed=01 complete in 50.8s

Number of Features: 1, Score: 0.082

Number of Features: 10, Score: 0.730

Number of Features: 19, Score: 0.825

Number of Features: 20, Score: 0.825

Number of Features: 100, Score: 0.735

Number of Features: 1, Score: 0.122

Number of Features: 10, Score: 0.678

Number of Features: 19, Score: 0.797

Number of Features: 20, Score: 0.803

Number of Features: 100, Score: 0.795

regression seed=02 complete in 48.5s

Number of Features: 1, Score: 0.105

Number of Features: 10, Score: 0.685

Number of Features: 19, Score: 0.800

Number of Features: 20, Score: 0.809

Number of Features: 100, Score: 0.760

Number of Features: 1, Score: 0.115

Number of Features: 10, Score: 0.688

Number of Features: 19, Score: 0.819

Number of Features: 20, Score: 0.830

Number of Features: 100, Score: 0.796

regression seed=03 complete in 49.6s

Number of Features: 1, Score: 0.088

Number of Features: 10, Score: 0.601

Number of Features: 19, Score: 0.765

Number of Features: 20, Score: 0.761

Number of Features: 100, Score: 0.705

Number of Features: 1, Score: 0.107

Number of Features: 10, Score: 0.648

Number of Features: 19, Score: 0.787

Number of Features: 20, Score: 0.789

Number of Features: 100, Score: 0.791

regression seed=04 complete in 47.7s

Number of Features: 1, Score: 0.112

Number of Features: 10, Score: 0.588

Number of Features: 19, Score: 0.783

Number of Features: 20, Score: 0.786

Number of Features: 100, Score: 0.729

Number of Features: 1, Score: 0.118

Number of Features: 10, Score: 0.646

Number of Features: 19, Score: 0.822

Number of Features: 20, Score: 0.819

Number of Features: 100, Score: 0.790

regression seed=05 complete in 51.3s

Number of Features: 1, Score: 0.103

Number of Features: 10, Score: 0.598

Number of Features: 19, Score: 0.786

Number of Features: 20, Score: 0.781

Number of Features: 100, Score: 0.730

Number of Features: 1, Score: 0.122

Number of Features: 10, Score: 0.720

Number of Features: 19, Score: 0.817

Number of Features: 20, Score: 0.820

Number of Features: 100, Score: 0.797

regression seed=06 complete in 43.3s

Number of Features: 1, Score: 0.100

Number of Features: 10, Score: 0.637

Number of Features: 19, Score: 0.778

Number of Features: 20, Score: 0.780

Number of Features: 100, Score: 0.751

Number of Features: 1, Score: 0.098

Number of Features: 10, Score: 0.598

Number of Features: 19, Score: 0.802

Number of Features: 20, Score: 0.802

Number of Features: 100, Score: 0.797

regression seed=07 complete in 52.0s

Number of Features: 1, Score: 0.149

Number of Features: 10, Score: 0.630

Number of Features: 19, Score: 0.808

Number of Features: 20, Score: 0.810

Number of Features: 100, Score: 0.797

Number of Features: 1, Score: 0.119

Number of Features: 10, Score: 0.648

Number of Features: 19, Score: 0.826

Number of Features: 20, Score: 0.835

Number of Features: 100, Score: 0.808

regression seed=08 complete in 62.3s

Number of Features: 1, Score: 0.221

Number of Features: 10, Score: 0.716

Number of Features: 19, Score: 0.847

Number of Features: 20, Score: 0.851

Number of Features: 100, Score: 0.775

Number of Features: 1, Score: 0.111

Number of Features: 10, Score: 0.636

Number of Features: 19, Score: 0.807

Number of Features: 20, Score: 0.811

Number of Features: 100, Score: 0.789

regression seed=09 complete in 50.4s

Number of Features: 1, Score: 0.069

Number of Features: 10, Score: 0.678

Number of Features: 19, Score: 0.784

Number of Features: 20, Score: 0.780

Number of Features: 100, Score: 0.742

Number of Features: 1, Score: 0.124

Number of Features: 10, Score: 0.656

Number of Features: 19, Score: 0.796

Number of Features: 20, Score: 0.812

Number of Features: 100, Score: 0.791

regression seed=10 complete in 45.5s

Number of Features: 1, Score: 0.077

Number of Features: 10, Score: 0.591

Number of Features: 19, Score: 0.774

Number of Features: 20, Score: 0.779

Number of Features: 100, Score: 0.750

Number of Features: 1, Score: 0.125

Number of Features: 10, Score: 0.672

Number of Features: 19, Score: 0.807

Number of Features: 20, Score: 0.811

Number of Features: 100, Score: 0.792

regression seed=11 complete in 44.6s

Number of Features: 1, Score: 0.086

Number of Features: 10, Score: 0.679

Number of Features: 19, Score: 0.791

Number of Features: 20, Score: 0.797

Number of Features: 100, Score: 0.756

Number of Features: 1, Score: 0.108

Number of Features: 10, Score: 0.618

Number of Features: 19, Score: 0.814

Number of Features: 20, Score: 0.823

Number of Features: 100, Score: 0.807

regression seed=12 complete in 44.2s

Number of Features: 1, Score: 0.122

Number of Features: 10, Score: 0.648

Number of Features: 19, Score: 0.808

Number of Features: 20, Score: 0.810

Number of Features: 100, Score: 0.740

Number of Features: 1, Score: 0.083

Number of Features: 10, Score: 0.655

Number of Features: 19, Score: 0.783

Number of Features: 20, Score: 0.791

Number of Features: 100, Score: 0.791

regression seed=13 complete in 48.1s

Number of Features: 1, Score: 0.079

Number of Features: 10, Score: 0.573

Number of Features: 19, Score: 0.760

Number of Features: 20, Score: 0.772

Number of Features: 100, Score: 0.753

Number of Features: 1, Score: 0.116

Number of Features: 10, Score: 0.665

Number of Features: 19, Score: 0.804

Number of Features: 20, Score: 0.806

Number of Features: 100, Score: 0.795

regression seed=14 complete in 117.3s

Number of Features: 1, Score: 0.082

Number of Features: 10, Score: 0.508

Number of Features: 19, Score: 0.757

Number of Features: 20, Score: 0.766

Number of Features: 100, Score: 0.732

Number of Features: 1, Score: 0.136

Number of Features: 10, Score: 0.673

Number of Features: 19, Score: 0.804

Number of Features: 20, Score: 0.809

Number of Features: 100, Score: 0.802

regression seed=15 complete in 94.0s

Number of Features: 1, Score: 0.092

Number of Features: 10, Score: 0.676

Number of Features: 19, Score: 0.825

Number of Features: 20, Score: 0.827

Number of Features: 100, Score: 0.766

Number of Features: 1, Score: 0.095

Number of Features: 10, Score: 0.698

Number of Features: 19, Score: 0.813

Number of Features: 20, Score: 0.822

Number of Features: 100, Score: 0.799

regression seed=16 complete in 62.2s

Number of Features: 1, Score: 0.098

Number of Features: 10, Score: 0.623

Number of Features: 19, Score: 0.771

Number of Features: 20, Score: 0.773

Number of Features: 100, Score: 0.742

Number of Features: 1, Score: 0.117

Number of Features: 10, Score: 0.661

Number of Features: 19, Score: 0.789

Number of Features: 20, Score: 0.795

Number of Features: 100, Score: 0.782

regression seed=17 complete in 52.4s

Number of Features: 1, Score: 0.226

Number of Features: 10, Score: 0.700

Number of Features: 19, Score: 0.802

Number of Features: 20, Score: 0.810

Number of Features: 100, Score: 0.740

Number of Features: 1, Score: 0.138

Number of Features: 10, Score: 0.695

Number of Features: 19, Score: 0.815

Number of Features: 20, Score: 0.814

Number of Features: 100, Score: 0.802

regression seed=18 complete in 53.3s

Number of Features: 1, Score: 0.133

Number of Features: 10, Score: 0.667

Number of Features: 19, Score: 0.812

Number of Features: 20, Score: 0.815

Number of Features: 100, Score: 0.758

Number of Features: 1, Score: 0.112

Number of Features: 10, Score: 0.737

Number of Features: 19, Score: 0.838

Number of Features: 20, Score: 0.835

Number of Features: 100, Score: 0.801

regression seed=19 complete in 55.3s

,task,seed,method,selected_architecture,selection_set_score,num_features,roc_auc,f1,balanced_accuracy,accuracy,r2,rmse,mae,pearson_r2
0,classification,0,svm_set,unified,0.911630,10,0.971273,0.894737,0.904633,0.904,NaN,NaN,NaN,NaN
1,classification,0,unified,unified,0.924451,10,0.962474,0.888889,0.899068,0.896,NaN,NaN,NaN,NaN
2,classification,0,training_selected,unified,0.924451,10,0.962474,0.888889,0.899068,0.896,NaN,NaN,NaN,NaN
3,classification,1,svm_set,svm_set,0.917125,10,0.966615,0.886957,0.897386,0.896,NaN,NaN,NaN,NaN
4,classification,1,unified,svm_set,0.906136,10,0.976190,0.915254,0.924172,0.920,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,regression,18,unified,unified,0.853795,19,NaN,NaN,NaN,NaN,0.801790,0.380499,0.308796,0.807718
116,regression,18,training_selected,unified,0.853795,19,NaN,NaN,NaN,NaN,0.801790,0.380499,0.308796,0.807718
117,regression,19,svm_set,svm_set,0.830462,19,NaN,NaN,NaN,NaN,0.776552,0.403998,0.311913,0.777323
118,regression,19,unified,svm_set,0.804852,19,NaN,NaN,NaN,NaN,0.804567,0.377824,0.297931,0.806903
119,regression,19,training_selected,svm_set,0.830462,19,NaN,NaN,NaN,NaN,0.776552,0.403998,0.311913,0.777323

In [2]:
classification_summary = results.query("task == 'classification'").groupby('method')[['roc_auc', 'f1', 'balanced_accuracy', 'accuracy']].agg(['mean', 'std'])
classification_summary.round(4)

                  roc_auc              f1         balanced_accuracy          \
                     mean     std    mean     std              mean     std
method
svm_set            0.9679  0.0049  0.8856  0.0155            0.8961  0.0146
training_selected  0.9677  0.0073  0.8952  0.0179            0.9052  0.0169
unified            0.9667  0.0082  0.9001  0.0148            0.9097  0.0143

                  accuracy
                      mean     std
method
svm_set             0.8948  0.0147
training_selected   0.9016  0.0162
unified             0.9052  0.0147

In [3]:
regression_summary = results.query("task == 'regression'").groupby('method')[['r2', 'rmse', 'mae', 'pearson_r2']].agg(['mean', 'std'])
regression_summary.round(4)

                       r2            rmse             mae         pearson_r2  \
                     mean     std    mean     std    mean     std       mean
method
svm_set            0.7811  0.0077  0.3998  0.0070  0.3132  0.0042     0.7818
training_selected  0.7915  0.0126  0.3901  0.0119  0.3082  0.0070     0.7936
unified            0.8065  0.0070  0.3759  0.0068  0.3006  0.0062     0.8110


                      std
method
svm_set            0.0078
training_selected  0.0142
unified            0.0062

In [4]:
selection = (results.query("method == 'training_selected'")
             .groupby(['task', 'selected_architecture']).size()
             .rename('count').to_frame())
selection

                                      count
task           selected_architecture
classification svm_set                    6
               unified                   14
regression     svm_set                   13
               unified                    7

In [5]:
paired = []
for task, metric in [('classification', 'roc_auc'), ('regression', 'r2')]:
    wide = results.query('task == @task').pivot(index='seed', columns='method', values=metric)
    for method in ['unified', 'training_selected']:
        delta = wide[method] - wide['svm_set']
        paired.append({'task': task, 'method_vs_set': method, 'mean_difference': delta.mean(),
                       'wins': (delta > 0).sum(), 'ties': (delta == 0).sum(), 'losses': (delta < 0).sum()})
import pandas as pd
pd.DataFrame(paired)

             task      method_vs_set  mean_difference  wins  ties  losses
0  classification            unified        -0.001216     8     0      12
1  classification  training_selected        -0.000298     5     6       9
2      regression            unified         0.025435    20     0       0
3      regression  training_selected         0.010392     7    13       0